### ISSUE TITLE
Feature: Always render

### ISSUE THREAD

**Issue by yoyurec** [vipzhicheng/logseq-plugin-block-calendar#1]
Is it possible to avoid adding it manually every time to have an option in plugin settings to render the calendar always on specified place?

**Comment by yoyurec** [comment]
or is it possible to export `setCal` globally to reuse in other plugins?

**Comment by yoyurec** [comment]
While I'm searching for a solution - I've added Banner plugins support with rendering to prepared place.
https://github.com/vipzhicheng/logseq-plugin-block-calendar/pull/3

**Comment by vipzhicheng** [comment]
A new version released, so close this issue for now.
