### ISSUE TITLE
Feature Request - Dot conveys overall task status for a Day

### ISSUE THREAD

**Issue by adxsoft** [vipzhicheng/logseq-plugin-block-calendar#10]
Great plugin .. thanks for the hard work on this. 

I've used Obsidian previously and one very nice feature was that the Calendar dots would indicate the following

![Obsidian Calendar](https://user-images.githubusercontent.com/24862237/181691398-5f9581a4-9e5d-401d-a90f-a23481a4763f.png)

- presence of a dot meant the journal page existed (your red dot does that now)
- a second dot for TODO status
  - open tasks (TODO) items exist on this journal - the second dot is hollow
  - no open tasks on this journal - the second dot is filled.

Another approach for Logseq that would not require two dots might be to have 3 different colors for a single dot
- white(or black for light mode) - page exists and has NO TODOs or DONE items for the day  (July 4 and 22)
- red - page exists and has open TODO items in it (July 17, 18, 23, 26, 28, 29 and 30)
- green - page exists and has only DONE items (July 6, 12, 14 and 19)

![Calendar with TODO status colors](https://user-images.githubusercontent.com/24862237/181690669-b20901a4-b3fe-4499-a38f-7ff52e695113.png)

**Comment by vipzhicheng** [comment]
Good idea, I will think about it and do some tests first. The final release may not be that fast.

**Comment by adxsoft** [comment]
Thanks for your consideration.

**Comment by vipzhicheng** [comment]
The feature has been implemented, please take a look.

![image](https://user-images.githubusercontent.com/1209538/189571835-5afa58bf-a603-46f2-93ee-090ec519ee02.png)
