### ISSUE TITLE
FR: Ability to set height and width of the calendar

### ISSUE THREAD

**Issue by AvijeetPrasad** [vipzhicheng/logseq-plugin-block-calendar#11]
Hi,

Thanks for this great plugin. Really liking it! It would be really nice, if we can also have the ability to set the width and height of the calendar. That way we can adjust it's layout in wider screens for example.

**Comment by xoyk** [comment]
@AvijeetPrasad I've solved it for myself via custom.css 

`.logseq-block-calendar {
    max-width: 400px;
    min-width: 315px;
}

#calendar-placeholder {
    display: flex;
    justify-content: center;
}`

that is example, how to set minimum and maximum width for calendar and center it in the sidebar. 
You can adjust the styles for your needs.
