### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by yoyurec** [vipzhicheng/logseq-plugin-block-calendar#13]
```
index.3edbe1a8.js:10 Uncaught (in promise) Error: [deferred timeout] undefined
    at index.3edbe1a8.js:10
```

![image](https://user-images.githubusercontent.com/137919/183244217-9eb71aa8-e77e-4a1b-b393-d4422fad3d8f.png)

**Comment by vipzhicheng** [comment]
Seems this is a Logseq Core issue. Many plugins throw these kind of errors.

**Comment by stdword** [comment]
@vipzhicheng, the same error for me. It disappers, whis plugin disabling → I guess it relates to some setTimeout handlers

**Comment by vipzhicheng** [comment]
Thanks to all of u. I have fixed this issue. Please update.
