### ISSUE TITLE
Switching to new graph leaves old graph calendar in side bar

### ISSUE THREAD

**Issue by adxsoft** [vipzhicheng/logseq-plugin-block-calendar#18]
I use several graphs and noticed if I am in graph1 the block calendar displays in the right panel at the top which is expected. 

If I change to graph2 the block calendar for graph1 remains displayed at the top of the right panel and the block calendar for graph2 is displayed underneath the graph1 calendar. 

Closing the right sidebar and re-opening it will make the graph1 block calendar disappear and the graph2 block calendar move to the top of the right panel.

**Comment by vipzhicheng** [comment]
Seems this issue has been fixed. I can not reproduce it anymore.
