### ISSUE TITLE
Clicked date results in display of date one day previous to selection

### ISSUE THREAD

**Issue by rosslaird** [vipzhicheng/logseq-plugin-block-calendar#19]
When I click on a date in the block calendar (0.1.8), whether through a directly rendered calendar on a given page or in the context of the banners plugin, the journal page that I am taken to is one day _before_ the day that I clicked. For example, when I click on October 20, I am delivered to the journal page for October 19. This persists through a restart of Logseq and changing the weekly start date settings (and reloading/restarting).

**Comment by rosslaird** [comment]
Related to #17. I've discovered that this mismatch only happens if I click on a date after the 9th of a given month.

**Comment by lilakk** [comment]
Yeah I have the same issue. This is a very handy plugin and it'd be great if this can be fixed soon.

**Comment by vipzhicheng** [comment]
It's fixed now, please upgrade and confirm.

**Comment by gmalone** [comment]
Still, going to wrong dates > 9 after updating.  v 0.1.11 😥  BTW, thanks for excellent plugin.

**Comment by vipzhicheng** [comment]
I guess It's related to timezone. could you tell me your timezone?

**Comment by gmalone** [comment]
I'm in US Mountain time zone.  GMT -7

Not sure the time zone is the issue, though, but you can verify.  Others reporting this issue are clearly from different time zones, yet report the same issue... clicking on the calendar dates (after the 9th of every month) goes to the wrong journal date... 1 day earlier than it should.

Once you spot the issue in the code you'll say "Ah hah! Found it!" (one of the best things about coding)

day-of-month >= 10 points to wrong date

Thanks for looking into it. And thanks for the super useful plugin. :)

**Comment by rosslaird** [comment]
I'm on PST (GMT—8).

**Comment by ahpatel** [comment]
My timezone is EST (GMT -5) and I am also still experiencing the issue.

**Comment by cleanclothes-pi** [comment]
Reporting back that with v0.1.12 update selecting a date in block calendar now opens the correct journal page.

**Comment by gmalone** [comment]
Thank for working on this.  Sorry to report, **no change in function**.  I updated to 0.1.12, restarted Logseq, and no change. See attached video.  Thanks for persisting.  It's a worthy plugin.

https://user-images.githubusercontent.com/3749543/209976400-dc60f99b-9771-4a23-a7de-5d26639bf508.mp4

**Comment by gmalone** [comment]
Attaching screenshot of installed plugins. Just in case there's a conflict.
![Eex7mStcvN](https://user-images.githubusercontent.com/3749543/209985957-b81076cd-f986-4df2-a93b-a2f0463bb29b.png)

**Comment by gmalone** [comment]
Yo, bought you some coffee. ☕☕☕  Thanks for the work on the plugin(s).

**Comment by vipzhicheng** [comment]
> Yo, bought you some coffee. ☕☕☕ Thanks for the work on the plugin(s).

Thanks for your support, I still can not reproduce this issue, but I tried another way in the timezone direction. Please have a try.

**Comment by dwrhodes** [comment]
I think you've got it this time. I'm in PST (GMT -8). I can click on any date and they all come up correctly.
