### ISSUE TITLE
Mistakes in french version of the calendar

### ISSUE THREAD

**Issue by bepolymathe** [vipzhicheng/logseq-plugin-block-calendar#20]
Hi @vipzhicheng 

Thanks for this great tool ! 
I juste want to report 2 mistakes in french version of the calendar. 

![image](https://user-images.githubusercontent.com/29939805/198836450-4a2acfef-59f1-4c04-b00e-fb5747f5e930.png)

Why only "Mardi" is an entire word and not "Mar" (3 letters) like the other ?
"Soleil" ("sun" in french) replace "Dimanche" ("sunday")... strange too. 
Could you make modifications ?
Thanks !

**Comment by vipzhicheng** [comment]
Yes, I totally can not understand the French language. So I really need someone like you to point out my mistakes. Thx. WIll do the modification in the next release.

**Comment by bepolymathe** [comment]
Thank you. If I can contribute it is with pleasure. Thanks to you !

**Comment by bepolymathe** [comment]
It works ! Thanks. Merci ;-)

**Comment by vipzhicheng** [comment]
De rien 😄
