### ISSUE TITLE
Wrong calendar display 🙀

### ISSUE THREAD

**Issue by bepolymathe** [vipzhicheng/logseq-plugin-block-calendar#21]
Hi @vipzhicheng 

I just realized that the calendar doesn't have a fair display.
I have the "Monday" option as the first day.

![image](https://user-images.githubusercontent.com/29939805/199686125-d0b15ed0-488c-42dc-b020-b80d286d2dab.png)

But the calendar is wrong. He considers that January 1 is a Monday and shifts everything.

What I see in logseq...

![image](https://user-images.githubusercontent.com/29939805/199686512-51744b2c-556e-4dff-9bc4-af431eddb9bc.png)

What the real calendar is

![image](https://user-images.githubusercontent.com/29939805/199686892-d550fa20-f2ce-48a2-ba0c-72fffb52d6b4.png)

It is the transition to the new year that seems to be the problem.

![image](https://user-images.githubusercontent.com/29939805/199689530-e4d62502-1f52-4494-8ccf-bb3a9712593e.png)

**Comment by vipzhicheng** [comment]
Thx, it's a bug, have fixed it maybe. Please upgrade the plugin and have a try.

**Comment by bepolymathe** [comment]
Yes it works ! Thanks !
