### ISSUE TITLE
Weekend display

### ISSUE THREAD

**Issue by bepolymathe** [vipzhicheng/logseq-plugin-block-calendar#22]
Hi @vipzhicheng 

I do not know if it is an aesthetic choice or a problem but the calendar integrating in the plugin "banner" is always displayed with a first colomne shift for Saturday and another a little larger for Sunday.
 
![image](https://user-images.githubusercontent.com/29939805/199688728-f1911184-888e-4855-ae8c-811c384b2437.png)

I find this a little surprising. Is it voluntary ?

**Comment by vipzhicheng** [comment]
It's fixed now. please upgrade
