### ISSUE TITLE
right click copy date link

### ISSUE THREAD

**Issue by marcocolnaghi** [vipzhicheng/logseq-plugin-block-calendar#24]
Hi, 
thanks for your nice plugin!

I suggest this simple **feature**: 
**right click on a day copies to clipboard the day link.**

This allows the user to put day reminders simply pasting it in a block

i.e. 
in my logseq I have date format YYYYMMDD

**left click** on 13 December opens the page
20221213

it would be very useful if 
**right click** on 13 December puts in clipboard [[20221213]] 

Thanks

**Comment by vipzhicheng** [comment]
I need to ask Logseq Team. As I tested, I can not catch the right click event using current API.

**Comment by marcocolnaghi** [comment]
Hi Richard,
thanks for your kind reply,
I understand.
For desktop could it be possible
to use Ctr+Click for date copy?

Thanks,
Marco.

**Comment by vipzhicheng** [comment]
Hey, I just release a version, it now supports `cmd+click` on Mac and `ctrl+click` on Windows to copy the calendar date to the clipboard. But for the current version I did not add `[[` and `]]` to surround the date, I guess someone may not need this.

What do you think. It's OK or need an option to let you can copy `[[20221213]]` format to the clipboard?
