### ISSUE TITLE
Error Message in console

### ISSUE THREAD

**Issue by adxsoft** [vipzhicheng/logseq-plugin-block-calendar#25]
get the following error message in the console

#logseq-block-calendar logseq-plugin-block-calendar can not resolve selector target #calendar-placeholder

Not sure if this is related to dots appearing under dates even though they have no TODO's

Using Logseq 8.14 on Mac OSX 10.13

**Comment by vipzhicheng** [comment]
This error is not serious, but a bug. I have fixed it, please upgrade.
