### ISSUE TITLE
FR: Shift click on a date to open it in the right sidebar

### ISSUE THREAD

**Issue by AvijeetPrasad** [vipzhicheng/logseq-plugin-block-calendar#30]
Hi,

Thanks for making this useful plugin. Currently, shift-clicking on any date opens it in the main window. It would be great to have the option to `shift-click` on a date to open it directly in the right sidebar. This would give us more flexibility in quickly browsing through multiple journal entries while working on a note in the main window.

**Comment by vipzhicheng** [comment]
Updated, please upgrade and take a look.

**Comment by AvijeetPrasad** [comment]
It works pretty well. Thank you!
