### ISSUE TITLE
How did you make the Notion-like blocks possible?

### ISSUE THREAD

**Issue by NickoJow** [vipzhicheng/logseq-plugin-block-calendar#31]
@vipzhicheng Hello, I saw from your demo that you were able to present a 4*3 stack of blocks in the yearly view of block calendar. I'm really curious of the way you made it possible. Did you make it by adjusting CSS or using a Plugin? I did some work of searching, but found no plugins or elaborate tutorial of the sort. Hope to hear from you. Appreciate it. Great work by the way.

**Comment by vipzhicheng** [comment]
It's just CSS, there is API to insert CSS to Logseq main window.

**Comment by NickoJow** [comment]
Understood. thought maybe so. thanks
