### ISSUE TITLE
Wrong calendar display

### ISSUE THREAD

**Issue by xxchan** [vipzhicheng/logseq-plugin-block-calendar#32]
The plugin looks great, but it doesn't seem to render correctly on my Logseq 🤔 

<img width="1300" alt="image" src="https://user-images.githubusercontent.com/37948597/235436893-d74dc9c0-5b6d-4d6b-a2c7-9df79c6bf18b.png">

**Comment by vipzhicheng** [comment]
The most likely reason is that it is not compatible with your current theme, you can try to change theme to default or adjust your local custom CSS for your own.
