### ISSUE TITLE
block calendar not showing up at the banner

### ISSUE THREAD

**Issue by jobatop** [vipzhicheng/logseq-plugin-block-calendar#36]
Hi,

I installed both Banner and Block Calendar, both working fine till this morning, the block calendar didn't show up. I don't know where is the problem, so I had another post at the banners page.
![Screenshot from 2024-01-01 12-24-20](https://github.com/vipzhicheng/logseq-plugin-block-calendar/assets/52852348/7c4f365f-687b-4268-a0e7-dcf9c45529bd)

I tried both plugin in a new graph, not working.

I reinstalled both plugin, still no working.

Check console, everything fine.

thank you for any hints

**Comment by stdword** [comment]
Same issue for me

**Comment by jobatop** [comment]
here is a fix, https://discuss.logseq.com/t/block-calendar-not-showing/24083/6

**Comment by gissehel** [comment]
I've experienced the same problem.
As a workaround, waiting for new version including the fix, you can specify explicitly year and month like this:
`{{renderer block-calendar,2024,1}}` (which won't "change month" on february, but let's hope that the problem will be fixed by then...)

**Comment by adxsoft** [comment]
Same issue for me. workaround above works well. I've just put `{{renderer block-calendar,2024,1` at the top of my 'contents' page/ Have to do that for each of my graphs. Will be nice when the plugin is fixed so don't have to change multiple graphs (I have 12 graphs).

**Comment by stdword** [comment]
@adxsoft, [here](https://discuss.logseq.com/t/block-calendar-not-showing/24083/5?u=stdword) is quick workaround. You need to do it once.

**Comment by adxsoft** [comment]
Great that worked! Thanks

**Comment by wensonsmith** [comment]
@stdword 

Thanks! Nice workaround

**Comment by AI-Ahmed** [comment]
> @adxsoft, [here](https://discuss.logseq.com/t/block-calendar-not-showing/24083/5?u=stdword) is quick workaround. You need to do it only once for all graphs.

It works! Thanks!

**Comment by vipzhicheng** [comment]
stdword's PR has been merged and released, please update, Sorry for the delay. Thanks @stdword
