### ISSUE TITLE
Unreadable calendar with Github dark theme

### ISSUE THREAD

**Issue by thinkh** [vipzhicheng/logseq-plugin-block-calendar#4]
Thanks for this nice plugin. I would like to use it in combination with the [Github dark theme](https://github.com/g1eny0ung/logseq-github-theme). Unfortunately, it is unreadable. Could you maybe (re-)use CSS variables to color the calendar, if you haven't already?

![grafik](https://user-images.githubusercontent.com/5851088/179472560-5aa0c291-1a43-4400-a960-b95d11004b23.png)

![grafik](https://user-images.githubusercontent.com/5851088/179472777-9bbb0cbd-66cb-4ec1-af91-2e777823a46e.png)

**Comment by vipzhicheng** [comment]
Will be fixed in next release.

**Comment by vipzhicheng** [comment]
A new version released, so close this issue for now.

**Comment by thinkh** [comment]
Thanks! 👍
