### ISSUE TITLE
Suggestion - Translation (PT-BR)

### ISSUE THREAD

**Issue by dlholdefer** [vipzhicheng/logseq-plugin-block-calendar#7]
Congratulations on the excellent plugin. It has been very helpful to me. Just a small correction. In the Portuguese language (PT-BR), Sunday is abbreviated as being as "Dom" and not as "Sol". 

`fa={January:"Janeiro",February:"Fevereiro",March:"Mar\xE7o",April:"Abril",May:"Maio",June:"Junho",July:"Julho",August:"Agosto",September:"Setembro",October:"Outubro",November:"Novembro",December:"Dezembro",Sunday:"Dom",Monday:"Seg",Tuesday:"Ter",Wednesday:"Qua",Thursday:"Qui",Friday:"Sex",Saturday:"S\xE1b",Today:"Hoje"}`

Thank you very much and success!

**Comment by vipzhicheng** [comment]
Thx, already fixed it in the new release.
